modLoader="javafml"
loaderVersion = "[36,)"
license="ARR"

[[mods]]
modId="pdgamerules"
version="${file.jarVersion}"
displayName="Per-Dimension Game Rules"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/per-world-game-rules-forge"
description="Adds dimensional game rules - /pdgamerule command"

[[dependencies.pdgamerules]]
    modId="kiwi"
    mandatory=true
versionRange = "[6,)"
    ordering="NONE"
    side="BOTH"
